export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const GRADES_REQUEST = 'GRADES_REQUEST'
export const GRADES_SUCCESS = 'GRADES_SUCCESS'
export const GRADES_FAIL = 'GRADES_FAIL'

export const GRADES_STUDENTS_REQUEST = 'GRADES_STUDENTS_REQUEST'
export const GRADES_STUDENTS_SUCCESS = 'GRADES_STUDENTS_SUCCESS'
export const GRADES_STUDENTS_FAIL = 'GRADES_STUDENTS_FAIL'
