export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const GRADES_REQUEST = 'GRADES_REQUEST'
export const GRADES_SUCCESS = 'GRADES_SUCCESS'
export const GRADES_FAIL = 'GRADES_FAIL'

export const GRADES_STUDENTS_REQUEST = 'GRADES_STUDENTS_REQUEST'
export const GRADES_STUDENTS_SUCCESS = 'GRADES_STUDENTS_SUCCESS'
export const GRADES_STUDENTS_FAIL = 'GRADES_STUDENTS_FAIL'

export const STUDENT_REQUEST = 'STUDENT_REQUEST'
export const STUDENT_SUCCESS = 'STUDENT_SUCCESS'
export const STUDENT_FAIL = 'STUDENT_FAIL'

export const STUDENT_SUBJECT_DELETE_REQUEST =
  'STUDENT_SUBJECT_DELETE_REQUEST'
export const STUDENT_SUBJECT_DELETE_SUCCESS =
  'STUDENT_SUBJECT_DELETE_SUCCESS'
export const STUDENT_SUBJECT_DELETE_FAIL =
  'STUDENT_SUBJECT_DELETE_FAIL'
export const STUDENT_SUBJECT_DELETE_DELETE =
  'STUDENT_SUBJECT_DELETE_DELETE'

export const STUDENT_SUBJECT_ADD_REQUEST =
  'STUDENT_SUBJECT_ADD_REQUEST'
export const STUDENT_SUBJECT_ADD_SUCCESS =
  'STUDENT_SUBJECT_ADD_SUCCESS'
export const STUDENT_SUBJECT_ADD_FAIL = 'STUDENT_SUBJECT_ADD_FAIL'
export const STUDENT_SUBJECT_ADD_DELETE = 'STUDENT_SUBJECT_ADD_DELETE'

export const TEACHER_REQUEST = 'TEACHER_REQUEST'
export const TEACHER_SUCCESS = 'TEACHER_SUCCESS'
export const TEACHER_FAIL = 'TEACHER_FAIL'
export const TEACHER_DELETE = 'TEACHER_DELETE'

export const TEACHER_SUBJECT_DELETE_REQUEST =
  'TEACHER_SUBJECT_DELETE_REQUEST'
export const TEACHER_SUBJECT_DELETE_SUCCESS =
  'TEACHER_SUBJECT_DELETE_SUCCESS'
export const TEACHER_SUBJECT_DELETE_FAIL =
  'TEACHER_SUBJECT_DELETE_FAIL'
export const TEACHER_SUBJECT_DELETE_DELETE =
  'TEACHER_SUBJECT_DELETE_DELETE'

export const TEACHER_SUBJECT_ADD_REQUEST =
  'TEACHER_SUBJECT_ADD_REQUEST'
export const TEACHER_SUBJECT_ADD_SUCCESS =
  'TEACHER_SUBJECT_ADD_SUCCESS'
export const TEACHER_SUBJECT_ADD_FAIL = 'TEACHER_SUBJECT_ADD_FAIL'
export const TEACHER_SUBJECT_ADD_DELETE = 'TEACHER_SUBJECT_ADD_DELETE'

export const TIMETABLE_REQUEST = 'TIMETABLE_REQUEST'
export const TIMETABLE_SUCCESS = 'TIMETABLE_SUCCESS'
export const TIMETABLE_FAIL = 'TIMETABLE_FAIL'

export const TIMETABLE_MODIFY_REQUEST = 'TIMETABLE_MODIFY_REQUEST'
export const TIMETABLE_MODIFY_SUCCESS = 'TIMETABLE_MODIFY_SUCCESS'
export const TIMETABLE_MODIFY_FAIL = 'TIMETABLE_MODIFY_FAIL'

export const TIMETABLE_UNASSIGN_REQUEST = 'TIMETABLE_UNASSIGN_REQUEST'
export const TIMETABLE_UNASSIGN_SUCCESS = 'TIMETABLE_UNASSIGN_SUCCESS'
export const TIMETABLE_UNASSIGN_FAIL = 'TIMETABLE_UNASSIGN_FAIL'
